{{ if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "extras.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "extras.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: aws-load-balancer-controller
        controlledValues: RequestsAndLimits
        mode: Auto
        minAllowed:
          cpu: 50m
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "extras.fullname" . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
